### ISSUE TITLE
BUG: Dead link

### ISSUE THREAD

**Issue by TommySorensen** [CrystallizeAPI/service-api-boilerplate#5]
Dead link in https://github.com/CrystallizeAPI/service-api-boilerplate/blob/main/src/services/payment-providers/klarna/capture.js#L5

Same goes for the documentation on https://crystallize.com/learn/developer-guides/order-api/the-order-object under the link "build your custom solution"

**Comment by hakonkrogh** [comment]
Thank you Tommy for reporting this. It is resolved now 🙂
