### ISSUE TITLE
Optional chaining breaks serverless to AWS

### ISSUE THREAD

**Issue by djclarkson** [CrystallizeAPI/service-api-boilerplate#9]
The following file specifies node runtime: nodejs12.x
service-api-boilerplate/platform-templates/serverless-aws/serverless.yml 

However, this will break with an "unexpected token" error due to the use of optional chaining on line 22 of the following file. 
service-api-boilerplate/src/services/payment-providers/stripe/confirm-order.js

To fix this runtime: nodejs14.x should be specified in the AWS serverless.yml file.

**Comment by hakonkrogh** [comment]
Thanks for the info @djclarkson. This is resolved in https://github.com/CrystallizeAPI/service-api-boilerplate/commit/c2bbaf9237cb0e3d3073db3856939afe38470f4e
